### ISSUE TITLE
How much vram do I need to train this model?

### ISSUE THREAD

**Issue by sullicsullic** [MCG-NJU/SparseOcc#13]
thanks for the great work~
The README model zoo tells that the training cost is 1d4h, ~12GB Memory.
But it runs out of memory when I train the r50_nuimg_704x256_8f model on one RTX4090.
I did not change anything in r50_nuimg_704x256_8f.py

What parameters should I decrease to train this model on a 24g vram machine?

**Comment by afterthat97** [comment]
you need 8 GPUs

**Comment by sullicsullic** [comment]
Hmmmm, are 4 gpus enough to train?

**Comment by afterthat97** [comment]
maybe

**Comment by afterthat97** [comment]
if that still not works, you can reduce num_frames to 6
