### ISSUE TITLE
the training at occupancy flow challenge (cvpr 2024)

### ISSUE THREAD

**Issue by GANWANSHUI** [MCG-NJU/SparseOcc#15]
hi, thanks a lot for the nice work.

I am trying to implement the sparseocc to [occupancy flow challenge (cvpr 2024)](https://github.com/OpenDriveLab/OccNet/tree/challenge), but the training result is not good, below is the result after 24 epochs on the validation dataset. 

**The details of the implementation simply replace the GT with the latest challenge GT, change the class number (18->17), and do not consider the flow training.** 

Have you tried to train on the latest challenge data? Thanks for any comments and suggestions. 

|     Class Names      | RayIoU@1 | RayIoU@2 | RayIoU@4 |
+----------------------+----------+----------+----------+
|         car          |  0.103   |  0.152   |  0.182   |
|        truck         |  0.044   |  0.077   |  0.107   |
|       trailer        |  0.024   |  0.038   |  0.059   |
|         bus          |  0.062   |  0.113   |  0.199   |
| construction_vehicle |  0.054   |  0.094   |  0.143   |
|       bicycle        |  0.000   |  0.000   |  0.000   |
|      motorcycle      |  0.000   |  0.000   |  0.000   |
|      pedestrian      |  0.000   |  0.001   |  0.001   |
|     traffic_cone     |  0.000   |  0.000   |  0.000   |
|       barrier        |  0.021   |  0.028   |  0.035   |
|  driveable_surface   |  0.112   |  0.164   |  0.225   |
|      other_flat      |  0.005   |  0.008   |  0.010   |
|       sidewalk       |  0.058   |  0.091   |  0.126   |
|       terrain        |  0.064   |  0.106   |  0.157   |
|       manmade        |  0.034   |  0.054   |  0.085   |
|      vegetation      |  0.020   |  0.036   |  0.063   |
+----------------------+----------+----------+----------+
|         MEAN         |  0.038   |  0.060   |  0.087   |
+----------------------+----------+----------+----------+

**Comment by afterthat97** [comment]
Hi, the performance on the challenge dataset should be almost the same as that on Occ3D. You can add my WeChat: 18061250030

**Comment by GANWANSHUI** [comment]
thank you!
