### ISSUE TITLE
请教下开集类别识别的问题

### ISSUE THREAD

**Issue by Qidian213** [MCG-NJU/SparseOcc#23]
不知道大佬有没有在研究开集类别的识别问题，毕竟目前还是受限于数据集的标注类别的。

**Comment by afterthat97** [comment]
目前没有在做这个，不过您说的很对🤔

**Comment by Qidian213** [comment]
最近探索了很多方法，包括尝试开源的2d相关的方案，基本还是基于clip的思想。测试效果在自动驾驶相关场景效果还是很有限，所以想请教下大佬的想法。

**Comment by afterthat97** [comment]
您可以加我微信 18061250030

**Comment by stickygao** [comment]
这个我们可以沟通下
