### ISSUE TITLE
Question about implementation of FB-OCC

### ISSUE THREAD

**Issue by LeeKeyu** [MCG-NJU/SparseOcc#26]
Hi, thanks for your great and impressive work! I would like to ask about the implementation of FB-OCC in your paper. The FPS is about 10 Hz as reported in your paper, while I observed that the FPS of FB-OCC implemented using the same A100 GPU was about 2 Hz (for example in this paper [OctreeOcc](https://github.com/4DVLab/OctreeOcc).
Could you please elaborate more on this discrepancy? Your advice will be of great help to me and other potential readers. Thanks in advance!

**Comment by afterthat97** [comment]
For FBOcc, we use the official config https://github.com/NVlabs/FB-BEV/blob/main/occupancy_configs/fb_occ/fbocc-r50-cbgs_depth_16f_16x4_20e.py and the provided weights to reproduce the results

Looks like OctreeOcc modified the setting? The input image size is set to 900×1600 and ResNet101-DCN is used as the image backbone, according to their paper.

**Comment by LeeKeyu** [comment]
May I ask how many GPUs did you use for evaluation? Thanks so much!

**Comment by afterthat97** [comment]
For evaluation, single gpu is enough

**Comment by LeeKeyu** [comment]
I see. Thank you for your answer!
