### ISSUE TITLE
Sensors used during inference

### ISSUE THREAD

**Issue by Hong753** [MCG-NJU/SparseOcc#30]
Hi, it seems that you are using the function sampling_4d which requires lidar2img transformations during evaluation as well.
It is my understanding that you proposed a method that uses only camera images during inference.
Please let me know if there's been a misunderstanding.

**Comment by afterthat97** [comment]
Yes, the projection matrix is also required.

**Comment by Hong753** [comment]
Issue is resolved. I confused the lidar point cloud with the actual lidar device.

**Comment by afterthat97** [comment]
We do not require lidar, but the projection matrix is still necessary
