### ISSUE TITLE
Install问题

### ISSUE THREAD

**Issue by stickygao** [MCG-NJU/SparseOcc#32]
如果我使用cuda11.8和torch2.0.0还是要下载mmcv-full1.6.0吗，我看mmcv官网这个组合只能使用mmcvfull 1.7.2了，或者可以使用mmcv2.0.0以上的版本吗，期待你们的回复，非常感谢

**Comment by stickygao** [comment]
已经点star了，非常喜欢你们的工作

**Comment by afterthat97** [comment]
mmcv 2.0改动太多了，肯定崩，1.7应该没问题

另外我还是建议你用1.6，虽然没有预编译的whl但它会自己编译

**Comment by stickygao** [comment]
![image](https://github.com/MCG-NJU/SparseOcc/assets/171310487/e4fb7a45-c8b6-4b3d-a40b-26d21c04f6d7)
所以这个你们也是使用torch2.0.0 cu118，然后mmcvfull1.6.0编译的吗

**Comment by afterthat97** [comment]
对

**Comment by stickygao** [comment]
thanks

**Comment by stickygao** [comment]
后面会release 可视化code吗

**Comment by afterthat97** [comment]
这不是已经release了
