### ISSUE TITLE
Questions about FPS tested on A100?

### ISSUE THREAD

**Issue by harrylin-hyl** [MCG-NJU/SparseOcc#35]
Wonderful work!
I also tested the speed of SparseOcc(8f) and FB-Occ on a A100 40G, but get some different results of the paper reported.
FB-OCC: 10.0 FPS and SparseOcc(8f): 17.3 FPS in the paper, but we got FB-OCC: 7.0 FPS and SparseOcc(8f): 17.8 FPS.
I want to know whether there are  some test settings different, especially the test of FB-OCC (we also followed the open-source code)?

**Comment by afterthat97** [comment]
Emmm I'm not sure :)
Maybe I turned on fp16 when testing FBOcc...
I have left OpenDriveLab and have no access to the previous data...
Anyway, the speed of SparseOcc is OK, glad to see you reproduced it :)

**Comment by harrylin-hyl** [comment]
Thanks for your reply!
