### ISSUE TITLE
loss_single 的疑问

### ISSUE THREAD

**Issue by FreqBayes** [MCG-NJU/SparseOcc#36]
Great Works! 
训练时发现 models/sparseocc_head.py 中的 SparseOCCHead.loss_single() 第97行，好像不太对，会导致后面匈牙利匹配中num_instances为空。调查之后可能是因为pytorch-1.10，torch.bincount(voxel_instances[b]) 如果 voxel_instances 中数据为 uint8 则结果异常。这里能不能改成 voxel_instances[b].long() 或者别的格式？

**Comment by afterthat97** [comment]
确实，我们也发现了这个bug，预计下个版本修复
建议你这几天先用torch 2.0，新版torch没有这个问题

**Comment by afterthat97** [comment]
修复了，感谢指出
