### ISSUE TITLE
已点赞：mmcv-full的版本怎么和pytorch2.0.0兼容的呢 

### ISSUE THREAD

**Issue by FeiT-FeiTeng** [MCG-NJU/SparseOcc#41]
非常感谢作者的出色工作：有一个小问题
官方镜像[https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html并没有mmcv-full](https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html%E5%B9%B6%E6%B2%A1%E6%9C%89mmcv-full) 1.6.0

**Comment by afterthat97** [comment]
你就按步骤装，他自己会编译的

**Comment by FeiT-FeiTeng** [comment]
好的，非常感谢~
目前我的问题是在安装

mim install mmcv-full==1.6.0

构建Wheel卡住不动。
我从pytorch开始重新安装一次。非常感谢您的建议！
________________________________

**Comment by afterthat97** [comment]
要编译好几分钟的，可以看一下cpu是否有占用率

**Comment by stickygao** [comment]
问题解决了吗，我会一直卡着直到超时

**Comment by afterthat97** [comment]
实在解决不了，用torch1.12/1.13+mmcv 1.6.0也是可以的

**Comment by afterthat97** [comment]
mmcv不能用2.0以上的，改动太大，不兼容

**Comment by stickygao** [comment]
1.7.0的mmcv可以吗

**Comment by afterthat97** [comment]
没试过，应该是可以的

**Comment by afterthat97** [comment]
但是mmdet3d必须要是v1.0.0rc6，他可能又会依赖特定的mmcv

**Comment by stickygao** [comment]
如果能提供docker就更好了

**Comment by afterthat97** [comment]
这个不难装呀，你肯定是服务器上的nvcc版本和conda里的cuda版本没对上

**Comment by afterthat97** [comment]
如果conda装的是cuda11，那你的nvcc也要是11.x的

**Comment by stickygao** [comment]
好像可以了编译时间确实很长，感谢你

**Comment by FeiT-FeiTeng** [comment]
感谢作者的解答，编译过程确实很长。也有一些小issues，不过pip一下就可以解决了。
