### ISSUE TITLE
Question about query_bbox 

### ISSUE THREAD

**Issue by autumn-wong** [MCG-NJU/SparseOcc#43]
Thank you for your excellent work!
While reading the code, I have a question. Why is the dimension of the query_bbox in SparseOcc [B, Q, 6]? It looks like it only uses xyz wlh and not additionally sin cos vx vy like SparseBEV. Is there any experiment shows that sin cos vx vy is not very useful in Occ tasks?

**Comment by YANG-CY-163** [comment]
The query in sparse_voxel_decoder corresponds to the voxels，and the query_bbox is related to voxel coords, and has nothing to do with velocity and angle , which is different from SparseBEV.

**Comment by autumn-wong** [comment]
Thank you for your response, I will close this issue.
