### ISSUE TITLE
sparse voxel怎么实现的

### ISSUE THREAD

**Issue by tangtaogo** [MCG-NJU/SparseOcc#48]
你好，感谢你们这么好的开源工作
<img width="796" alt="image" src="https://github.com/user-attachments/assets/ec5bd0bb-a291-4fcf-9845-4c9e86f81e1c">

我比较困惑怎么从image feat得到multi-level sparse voxel，哪里的代码对应的是multi-level sparse voxel呢，是用什么数据结构表达的multi-level sparse voxel是octree还是什么形式呢，我看SparseOccHead里面似乎没有找到multi-level sparse voxel在哪里，可以帮忙解答下么？感谢🙏

**Comment by YANG-CY-163** [comment]
multi-level sparse voxel部分的代码在models/sparse_voxel_decoder.py里，image feat的交互主要是通过SpaseVoxelDecoder里的SparseBEVSampling和AdaptiveMixing实现，可以结合代码理解一下

**Comment by tangtaogo** [comment]
感谢回复，所以其实没有显示的生成multi-level sparse voxel，是通过sampling来实现的对嘛

**Comment by YANG-CY-163** [comment]
有的，SpaseVoxelDecoder里的query_bbox和query_feat就是和voxel对应的，会经过upsample和sparsify操作（具体可以看models/sparse_voxel_decoder.py），sampling和mixing会更新query_feat, 可以看看SparseBEV了解更多细节

**Comment by tangtaogo** [comment]
非常感谢
