### ISSUE TITLE
About panoptic occupancy prediction

### ISSUE THREAD

**Issue by zgchen33** [MCG-NJU/SparseOcc#5]
Do you plan to release the code about panoptic occupancy prediction?

**Comment by afterthat97** [comment]
Yes of course! maybe a few days later

**Comment by zgchen33** [comment]
> Yes of course! maybe a few days later

Hope to see your code on this soon!

**Comment by afterthat97** [comment]
Hi, I have released the panoptic version.

**Comment by zgchen33** [comment]
> Hi, I have released the panoptic version.

Thank you so much, but I don't see the tool to calculate **RayPQ**. It would be better if you plan to release the tool.

**Comment by afterthat97** [comment]
oh, I forgot that. I will release it. sorry
