### ISSUE TITLE
question about class balanced

### ISSUE THREAD

**Issue by aiming1998** [MCG-NJU/SparseOcc#7]
Hi， thanks for your code!
![image](https://github.com/MCG-NJU/SparseOcc/assets/52338755/46e38530-ea1b-448b-87d6-fa71ebe397fd)
I noticed in the sparsev2 [paper]([](https://arxiv.org/pdf/2312.17118v2.pdf)) that category balancing is important, but I wonder if it is effective for dense occ method? If the current GT does not have some classes, the weight will be +inf. I tried to use it in dense OCC prediction and found that is harmful for miou.

**Comment by aiming1998** [comment]
Another question, I don't see that you used category balance in the semantic part of your code. Has this strategy been abandoned？

**Comment by afterthat97** [comment]
the class balanced CE is here:

https://github.com/MCG-NJU/SparseOcc/blob/b35e1d81d4bdbd7cc787f890f1c21885a754ac4f/models/loss_utils.py#L63

**Comment by aiming1998** [comment]
Is this part of the code only used for 2-cls occupancy pred?

**Comment by afterthat97** [comment]
yes
