### ISSUE TITLE
details about paper

### ISSUE THREAD

**Issue by CeoiZidung** [MCG-NJU/SparseOcc#9]
你好，在paper的Fig1(c)中，为什么FB-OCC的FPS比BEVDet4D-Occ还高呀？
按我的理解，FB-OCC有一个前向和反向投影的过程，而BEVDet4D-OCC只有一个反向投影的过程，不应该是BEVDet4D-OCC更快吗？

**Comment by afterthat97** [comment]
方法上看起来确实fb慢，但是实际上fb要快，可能因为他们网络中都用的100x100x8的occ分辨率。你自己也可以测测看
